### ISSUE TITLE
Before Trash Post Trigger

### ISSUE THREAD

**Issue by rashanoureldin** [wp-tip/wp-rules#84]
I created New Rule called Before trash trigger
its supposed to show admin notice and deleting options menu before sending any post type to trash after clicking trash post.
it didn't worked.
kindly find attached video explaining this issue in it 

https://www.awesomescreenshot.com/video/4895279?key=a826ccc68be54757b4ea2c5e67338c86

**Comment by engahmeds3ed** [comment]
Thanks @rashanoureldin 

This issue consists of two main issues:-

1. Using show notice action with a backend trigger that redirects automatically after firing, related to this one #80 
2. You used an action to delete an option that doesn't exist, keep in mind that this `options` means the site wp_options table that may be added from different plugins or from the core of WP, like the settings page.
